name: TruffleHog Secret Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  trufflehog:
    name: Run TruffleHog
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write  # Needed for SARIF upload

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run TruffleHog scan
        uses: trufflesecurity/trufflehog@v3.89.2
        with:
          scanArguments: --format sarif --output trufflehog-results.sarif || true

      - name: Upload TruffleHog results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: trufflehog-results.sarif
