name: TruffleHog Secret Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  trufflehog:
    name: Run TruffleHog
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write  # Needed to upload SARIF

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run TruffleHog scan and generate SARIF
        uses: trufflesecurity/trufflehog@v3.89.2
        with:
          extra_args: --format sarif --output trufflehog-results.sarif
        continue-on-error: true

      - name: Check SARIF exists
        run: test -f trufflehog-results.sarif || echo "SARIF file not found"

      - name: Upload SARIF to GitHub Code Scanning
        if: success() && steps.trufflehog.outputs.exitcode != '1'
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trufflehog-results.sarif
