name: OWASP ZAP Scan

on:
  workflow_dispatch:

jobs:
  zap-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Start Juice Shop container
        run: |
          docker run -d -p 3000:3000 --name juice-shop bkimminich/juice-shop:latest
          sleep 30  # wait for app to be ready

      # Optional: Authenticate with Docker Hub to avoid pull limits (recommended)
      - name: Docker login to Docker Hub
        if: env.DOCKER_USERNAME != '' && env.DOCKER_PASSWORD != ''
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin


      - name: Run OWASP ZAP baseline scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'http://localhost:3000'
          docker_name: 'owasp/zap2docker-stable'
          fail_action: true  # replaces the invalid `failOnError`

      - name: Stop Juice Shop container
        run: docker stop juice-shop && docker rm juice-shop
