name: OWASP ZAP Scan

on:
  workflow_dispatch:

jobs:
  zap-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Start Juice Shop container
        run: |
          docker run -d -p 3000:3000 --name juice-shop bkimminich/juice-shop:latest
          sleep 30

      - name: Docker login to GitHub Container Registry (GHCR)
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u "${{ secrets.GHCR_USER }}" --password-stdin

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'http://localhost:3000'
          docker_name: 'ghcr.io/zaproxy/zap-stable'
          fail_action: true  # This is the correct flag, not failOnError

      - name: Stop Juice Shop container
        run: docker stop juice-shop && docker rm juice-shop
