name: OWASP ZAP Scan

on:
  workflow_dispatch:

jobs:
  zap-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Start Juice Shop container
        run: |
          docker run -d -p 3000:3000 --name juice-shop bkimminich/juice-shop:latest
          sleep 30  # Wait for the app to be ready

      - name: Run OWASP ZAP baseline scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'http://localhost:3000'
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'

      - name: Convert ZAP report to SARIF
        run: |
          mkdir -p zap-sarif
          docker run --rm -v ${{ github.workspace }}:/zap ghcr.io/zaproxy/zaproxy:stable \
            zap-cli report -o /zap/zap-sarif/zap-output.sarif -f sarif

      - name: Upload ZAP results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: zap-sarif/zap-output.sarif

      - name: Stop Juice Shop container
        run: docker stop juice-shop && docker rm juice-shop
