name: OWASP ZAP Scan

on:
  workflow_dispatch:

jobs:
  zap-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Start Juice Shop container
        run: |
          docker run -d -p 3000:3000 --name juice-shop bkimminich/juice-shop:latest
          sleep 30  # wait for app to be ready

      - name: Docker login (if needed)
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin


      - name: Run OWASP ZAP baseline scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'http://localhost:3000'
          failOnError: 'true'

      - name: Stop Juice Shop container
        run: docker stop juice-shop && docker rm juice-shop
